### PR TITLE
Open Graph Meta: Update description and add default image

### LINKED ISSUE #442: Improve Open Graph properties throughout Developer Resources
Right now, and in the previous design, the Open Graph properties for each individual page in Developer Resources are all the same, and there is no thumbnail image. We should improve this post-launch.

| [Example 1](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeveloper.wordpress.org%2Fblock-editor%2F) | [Example 2](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeveloper.wordpress.org%2Fthemes%2F) |
|-|-|
|image|image|

cc @fcoveram @thetinyl for thoughts

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #442 — This adds unique descriptions to the handbooks and CLI command pages, using the excerpt for those pages, and improves the description for code reference archive pages. It also adds [the provided default image](https://github.com/WordPress/wporg-developer/issues/442#issuecomment-1862526706).

cc @ndiego @fcoveram @thetinyl @eidolonnight 

Here are the titles & descriptions as of the PR. Note that the `title` value is the same as in the `<title>…` tag rendered in the browser tab.

| Page | Title | Description |
|---|---|---|
| Homepage | WordPress Developer Resources &#124; Official WordPress Developer Resources &#124; Developer.WordPress.org | Official WordPress developer resources including a code reference, handbooks (for APIs, plugin and theme development, block editor), and more. |
| Code reference landing | Reference &#124; Developer.WordPress.org | Want to know what’s going on inside WordPress? Find out more information about its functions, classes, methods, and hooks. |
| [CR: "New in [version]" archive](https://developer.wordpress.org/reference/since/6.4.0/) | 6.4.0 &#124; Developer.WordPress.org | New and updated in 6.4.0 |
| [CR: functions archive](https://developer.wordpress.org/reference/functions/) | Functions &#124; Developer.WordPress.org | Code Reference archive for WordPress functions. |
| CR: hook | render_block_{$this->name} – Hook &#124; Developer.WordPress.org | Filters the content of a single block. |
| CR: function | get_theme_file_uri() – Function &#124; Developer.WordPress.org | Retrieves the URL of a file in the theme. |
| CR: class | WP_Query – Class &#124; Developer.WordPress.org | The WordPress Query class. |
| CR: method | WP_Query::have_posts() – Method &#124; Developer.WordPress.org | Determines whether there are more posts available in the loop. |
| Handbook front page | Block Editor Handbook &#124; Developer.WordPress.org | 👋 Welcome to the Block Editor Handbook. |
| Handbook page | Block API Reference – Block Editor Handbook &#124; Developer.WordPress.org | Blocks are the fundamental element of the editor. They are the primary way in which plugins and themes can register their own functionality… |
| CLI landing page | WP-CLI Commands &#124; Developer.WordPress.org | Documentation for all currently available WP-CLI commands, including usage and subcommands. |
| CLI command page | wp core – WP-CLI Command &#124; Developer.WordPress.org | Downloads, installs, updates, and manages a WordPress installation. |

Regarding the image, it's currently set to be used for all pages. I don't think we can easily do a custom image for each page (maybe in the future by using Jetpack's social images thing, but not now). We could create a few for each section, like a Code reference one, a Block Editor handbook one, etc. I can either update this PR or we can continue that idea in a new issue, if that sounds good.

### CODE REVIEW

**Comment by fcoveram** [comment]
I don't see the need to show images on certain pages. This looks good to me. But I'm not sure about using the wave emoji (👋), so waiting for comms folks to jump in and revisit the content.

**Comment by ryelle** [comment]
> But I'm not sure about using the wave emoji (👋), so waiting for comms folks to jump in and revisit the content.

Yeah, that's specifically because it's part of [the first sentence in the handbook](https://developer.wordpress.org/block-editor/). Removing it from the content in markdown would remove it here as well.

**Comment by ndiego** [comment]
> Yeah, that's specifically because it's part of [the first sentence in the handbook](https://developer.wordpress.org/block-editor/). Removing it from the content in markdown would remove it here as well.

I can take care of this 😉

**Review by outdoor2kode — APPROVED** [review]
Looks good to me 👍 

image

**Pull request merged**
