### PR TITLE
Hide commonly-used functions from the uses section.

### PR DESCRIPTION
**Pull request by dd32**
As noted in #21, the "Uses" section can get rather noisy when it includes functions that are used by, in some cases, 1,000 other functions.

This PR removes any function from that section that is used by more than 50 other functions. An arbitrary number I chose.

Example with https://developer.wordpress.org/reference/functions/wp_authenticate/

| Before | After |
| --- | --- |
| Screen Shot 2022-05-31 at 1 11 49 pm  | Screen Shot 2022-05-31 at 1 12 09 pm  | 

Leaving this as a PR as I'm not 100% sure on it. It might make more sense to keep them or sort it differently.. or.. make the functions clickable within the code source-view instead (like GitHub)

### CODE REVIEW

**Comment by tellyworth** [comment]
I think as long as the hooks themselves are displayed somewhere (whether in this list or a separate one) then this is a definite improvement.

I guess as an alternative the commonly-used functions could be pushed to the bottom below a Show More link.

**Comment by dd32** [comment]
> I think as long as the hooks themselves are displayed somewhere (whether in this list or a separate one) then this is a definite improvement.

Well, this isn't for removing the hooks from the table (That's already happened), just common WordPress functions - such as `__()` or `apply_filters()` which is used by nearly every function.

> I guess as an alternative the commonly-used functions could be pushed to the bottom below a Show More link.

That seems like a good middle-ground. Move all of the commonly-used functions to the bottom of the list, and hide them by default. Let me play with that.

**Comment by tellyworth** [comment]
My last commit partially implements the move-to-the-bottom idea. It returns a count of the number to display, but the JS still needs to be fixed (restored?) for the show/hide part to work.

**Comment by dd32** [comment]
> but the JS still needs to be fixed (restored?) for the show/hide part to work.

@tellyworth I've updated the JS to respect the count from PHP, appears to work now. 

| Default | Expanded |
| --- | --- |
| Screen Shot 2022-06-09 at 3 51 24 pm | Screen Shot 2022-06-09 at 3 51 28 pm |

**Pull request merged**
